### ISSUE TITLE
expired credentials

### ISSUE THREAD

**Issue by bollig** [aws-samples/no-tears-cluster#15]
```
Admin:~/environment $ pcluster update -c al2-config.ini hpc-cluster-al6
Retrieving configuration from CloudFormation for cluster hpc-cluster-al6...
ERROR: Failed when retrieving cluster config version from DynamoDB with error An error occurred (UnrecognizedClientException) when calling the GetItem operation: The security token included in the request is invalid
```

Note that ~/.aws/credentials exists on Cloud9 and contains: 
```
# Do not modify this file, if this file is modified it will not be updated. If the file is deleted, it will be recreated on Mon Oct 05 2020 23:48:15 GMT+0000 (Coordinated Universal Time).
# [...] #

[default]
aws_access_key_id=[...]
aws_secret_access_key=[...]
aws_session_token=[...]
region=us-east-1
```

**Comment by sean-smith** [comment]
We've seen this before, Cloud9 creds are short lived (5 mins) and it looks like you got unlucky on this one. We should probably setup an instance profile. 

We did this in the labs to solve this issue, see https://www.hpcworkshops.com/05-aws-batch/00-environment.html

**Comment by bollig** [comment]
Cloud9 refreshes the credentials and access is retained. Long running tasks using the API are the only thing impacted. Aside from `pcluster status`, I have not encountered other issues.
