### ISSUE TITLE
Cloud9 instance: no space left on device

### ISSUE THREAD

**Issue by rsignell-usgs** [aws-samples/no-tears-cluster#19]
I came back to my Cloud9 environment created by no-tears-cluster after a few weeks of inactivity and when I tried to login, I got `no space left on device`.   Is it doing some logging that fills up the disk during periods of inactivity?
Looks like the EBS volume is 10GB.    

I was able to do
```
yum clean packages
```
to free up enough space that I could store the `resize.sh` script mentioned in the [resize EBS instructions](https://docs.aws.amazon.com/cloud9/latest/user-guide/move-environment.html#move-environment-resize) but the script failed. 

Needless to say, a bit of a hurdle for a mere researcher.

**Comment by sean-smith** [comment]
What was the failure?

**Comment by sean-smith** [comment]
I tested the `resize.sh` script on my Cloud9 and it worked wonders, I wonder why yours failed 

```bash
$ sh resize.sh 20
resize.sh: line 1: !/bin/bash: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    19  100    19    0     0   1583      0 --:--:-- --:--:-- --:--:--  1583
{
    "VolumeModification": {
        "VolumeId": "vol-00489d7811454ff2e",
        "ModificationState": "modifying",
        "TargetSize": 20,
        "TargetIops": 100,
        "TargetVolumeType": "gp2",
        "OriginalSize": 10,
        "OriginalIops": 100,
        "OriginalVolumeType": "gp2",
        "Progress": 0,
        "StartTime": "2020-11-08T01:14:52.000Z"
    }
}
CHANGED: disk=/dev/xvda partition=1: start=4096 old: size=20967390,end=20971486 new: size=41938910,end=41943006
resize2fs 1.43.5 (04-Aug-2017)
Filesystem at /dev/xvda1 is mounted on /; on-line resizing required
old_desc_blocks = 1, new_desc_blocks = 2
The filesystem on /dev/xvda1 is now 5242363 (4k) blocks long.
```
