### ISSUE TITLE
failed build

### ISSUE THREAD

**Issue by zeekus** [aws-samples/no-tears-cluster#27]
I attempted to use the 'no tears' solution to build a 'test' HPC server with a $50 budget via the web interface. 

My build failed with the following: 
You have attempted to create more buckets than allowed (Service: Amazon S3; Status Code: 400; Error Code: TooManyBuckets; f

What is the lowest cost budget system I can create with this solution ?

**Comment by zeekus** [comment]
Seems there is a 100 s3 bucket default in AWS. We had over 100. I think this may be the cause of the error I saw. 
https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html

**Comment by bollig** [comment]
Yes, there is a hard limit of 100 S3 buckets on your account. You'll need to start a new account, or delete an existing bucket.
